### ISSUE TITLE
Note that this is designed to run as a PAL region game

### ISSUE THREAD

**Issue by peterwooley** [NesHacker/NesPi#3]
Hey! Thanks for the great videos and including this more complex example for all of us to play with.

When I was getting it up and running, I launched the ROM in FCEUX and thought I had broken something once I got to the Pi-calculation screen. It turns out I had FCEUX's region set to NTSC instead of PAL and it was generating the first line of Pi outside the bounds of the NTSC screen.

![image](https://user-images.githubusercontent.com/42030/223018811-1a989391-8d54-4e21-86db-f854c8f65807.png)

I'm not sure if there's a way to specify the region in an NES rom (that sounds like something Nintendo wouldn't have been worried about back then), but it may help others to add a note to the README saying that the built .nes rom should be run in an emulator set to the PAL region.

**Comment by rsandor** [comment]
So it looks like there is a way to specify a PAL vs. NTSC cart via the extended [iNES header](http://fms.komkon.org/EMUL8/NES.html#LABM), but it's unclear how well supported this. Wanna take a crack at updating the header and filing a PR?

**Comment by bunder2015** [comment]
Header looks okay to me...

![Screenshot_20230306_200117](https://user-images.githubusercontent.com/12985665/223292015-324b7921-0eb4-43fd-9ede-afcd287df162.png)

**Comment by rsandor** [comment]
I think it might just be an issue with some emulators (e.g. FCEUX) cutting off the top eight and bottom eight pixels by default when handling games for NTSC 🤔. With the current header it seems to run just fine on Mesen.

**Comment by zorchenhimer** [comment]
It runs fine, but it's usually a good idea to take into consideration the NTSC cropping (note that hardware doesn't know anything about headers).

That said, it would probably suffice to just mention it in the readme or something so people don't think it's not working.

![image](https://user-images.githubusercontent.com/6540297/223314354-c163d02f-fd99-42e7-832f-d79f8338de7b.png)

**Comment by rsandor** [comment]
@zorchenhimer Good idea, I'll add a note to the PR about NTSC cropping and link the PR to this ticket. Also: that is one really nice looking Famicom you got there 👍
